### ISSUE TITLE
`TypeError: _flash_attn_varlen_forward() missing 1 required positional argument: 'window_size'`

### ISSUE THREAD

**Issue by sidnb13** [RulinShao/FastCkpt#1]
From the call to `_flash_attn_varlen_forward()` on line 179 in `llama_flash_attn_ckpt_monkey_patch.py`, it looks like window_size is not specified. From [the documentation](https://github.com/Dao-AILab/flash-attention/blob/02ac572f3ffc4f402e4183aaa6824b45859d3ed3/README.md?plain=1#L112), would the default value of `window_size=(-1,-1)` be appropriate here?

**Comment by RulinShao** [comment]
Hi! `window_size` is only useful when you want to do sparse version of FlashAttention. By default, `window_size=(-1,-1)` means it will compute full attention. You're not supposed to see this error as it should just use the default setting. Please let me know if manually passing `window_size=(-1,-1)` can help. Thanks!

**Comment by sidnb13** [comment]
Yes, `window_size=(-1,-1)` resolved this as expected. Thanks for the clarification.
